# Generated by Django 5.2.10 on 2026-03-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('InProgress', 'In Progress'), ('Completed', 'Completed')], max_length=50),
        ),
    ]
