# Generated by Django 5.2.10 on 2026-03-05 17:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_education_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[("Bachelor's Degree", "Bachelor's Degree"), ('Professional Training', 'Professional Training'), ('Online Courses', 'Online Courses')], max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('InProgress', 'In Progress'), ('Completed', 'Completed')], default='InProgress', max_length=50),
        ),
        migrations.AlterField(
            model_name='languages',
            name='proficiency',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Native', 'Native')], max_length=50),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
