# Generated by Django 5.2.10 on 2026-03-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="project_image",
            field=models.ImageField(blank=True, null=True, upload_to="project_pictures/"),
        ),
    ]
